'use client'

import { useMemo, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import remarkMath from 'remark-math'
import rehypeKatex from 'rehype-katex'
import type { TFunction } from 'i18next'

import { Button } from '@/components/ui/button'
import type { LearningResource } from '@/lib/types/learning'
import { cn } from '@/lib/utils'

const ASSET_METADATA_START = '<!-- learning-asset'
const ASSET_METADATA_END = '-->'

type QuizQuestion = {
  id: string
  prompt: string
  options: string[]
  answer_index: number
  explanation: string
}

type Flashcard = {
  front: string
  back: string
  hint?: string
}

type MindMapNode = {
  id: string
  text: string
  level: number
  children: MindMapNode[]
}

type Token = {
  text: string
  className?: string
}

export type LearningAssetInteractionEvent = {
  eventType: string
  summary: string
}

const LEARNING_ASSET_KIND_LABELS: Record<string, string> = {
  study_guide: 'Study guide',
  quiz: 'Quiz',
  flashcards: 'Flashcards',
  mind_map: 'Mind map',
  reading: 'Reading',
  code_lab: 'Code lab',
}

export function getLearningAssetKindLabel(
  kind?: string | null,
  t?: TFunction<'translation', undefined>
) {
  if (!kind) {
    return 'Asset'
  }
  if (t) {
    const key = `learningAssets.kinds.${kind}`
    const translated = t(key)
    if (translated !== key) {
      return translated
    }
  }
  return LEARNING_ASSET_KIND_LABELS[kind] || kind
}

export function getLearningAssetTypeLabel(
  resource?: Pick<LearningResource, 'kind'> | null,
  t?: TFunction<'translation', undefined>
) {
  return getLearningAssetKindLabel(resource?.kind, t)
}

export function serializeLearningAssetNote(
  resource: LearningResource,
  kindLabel = getLearningAssetKindLabel(resource.kind)
) {
  const metadata = JSON.stringify({ ...resource, type: kindLabel })
  const extraSections: string[] = []
  const questions = getQuizQuestions(resource)
  const cards = getFlashcards(resource)

  if (resource.kind === 'quiz' && questions.length > 0) {
    extraSections.push(
      '## Quiz summary',
      questions
        .map(
          (question, index) =>
            `${index + 1}. ${question.prompt}\nAnswer: ${question.options[question.answer_index]}\nExplanation: ${question.explanation}`
        )
        .join('\n\n')
    )
  }

  if (resource.kind === 'flashcards' && cards.length > 0) {
    extraSections.push(
      '## Flashcards',
      cards
        .map(
          (card, index) =>
            `Card ${index + 1}\nFront: ${card.front}\nBack: ${card.back}`
        )
        .join('\n\n')
    )
  }

  const visibleContent = [
    `# ${resource.title}`,
    `Asset kind: ${kindLabel}`,
    `Type: ${kindLabel}`,
    `Format: ${resource.format}`,
    `Generated by: ${resource.agent}`,
    '',
    '## Objective',
    resource.summary,
    '',
    '## Content',
    resource.content,
    '',
    ...extraSections,
    '',
    `Tags: ${resource.tags.join(', ')}`,
  ].join('\n')

  return [ASSET_METADATA_START, metadata, ASSET_METADATA_END, '', visibleContent].join('\n')
}

export function parseLearningAssetNote(content?: string | null) {
  if (!content) {
    return null
  }

  const start = content.indexOf(ASSET_METADATA_START)
  if (start === -1) {
    return null
  }

  const metadataStart = start + ASSET_METADATA_START.length
  const end = content.indexOf(ASSET_METADATA_END, metadataStart)
  if (end === -1) {
    return null
  }

  const rawMetadata = content.slice(metadataStart, end).trim()
  try {
    return JSON.parse(rawMetadata) as LearningResource
  } catch {
    return null
  }
}

export function getVisibleLearningAssetContent(content?: string | null) {
  if (!content) {
    return ''
  }

  const start = content.indexOf(ASSET_METADATA_START)
  if (start === -1) {
    return content
  }

  const end = content.indexOf(ASSET_METADATA_END, start + ASSET_METADATA_START.length)
  if (end === -1) {
    return content
  }

  return content.slice(end + ASSET_METADATA_END.length).trim()
}

function getQuizQuestions(resource: LearningResource): QuizQuestion[] {
  const questions = resource.payload?.questions
  return Array.isArray(questions) ? (questions as QuizQuestion[]) : []
}

function getFlashcards(resource: LearningResource): Flashcard[] {
  const cards = resource.payload?.cards
  return Array.isArray(cards) ? (cards as Flashcard[]) : []
}

function tokenizeCodeLine(line: string): Token[] {
  const regex =
    /(\/\*[\s\S]*?\*\/|\/\/.*$)|("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|`(?:[^`\\]|\\.)*`)|\b(?:const|let|var|function|return|if|else|for|while|switch|case|break|continue|try|catch|finally|throw|new|class|import|from|export|default|await|async|this|super|extends|typeof|instanceof|true|false|null|undefined|NaN|Infinity|def|yield|interface|type|enum|readonly|public|private|protected|namespace|implements)\b|\b\d+(?:\.\d+)?\b|[{}[\]().,;+*\/=<>:!?\-]/g
  const tokens: Token[] = []
  let position = 0

  for (;;) {
    const next = regex.exec(line)
    if (!next) {
      if (position < line.length) {
        tokens.push({ text: line.slice(position) })
      }
      break
    }

    if (next.index > position) {
      tokens.push({ text: line.slice(position, next.index) })
    }

    const matchText = next[0]
    let className = ''
    if (next[1]) {
      className = 'text-emerald-600 dark:text-emerald-400'
    } else if (next[2]) {
      className = 'text-amber-700 dark:text-amber-300'
    } else if (next[3]) {
      className = 'text-blue-700 dark:text-blue-300'
    } else if (next[4]) {
      className = 'text-violet-600 dark:text-violet-300'
    } else if (next[5]) {
      className = 'text-rose-600 dark:text-rose-300'
    }

    tokens.push({
      text: matchText,
      className: className || undefined,
    })
    position = next.index + matchText.length
  }

  return tokens
}

function CodeHighlightedBlock({ code, language, compact, className }: {
  code: string
  language?: string
  compact: boolean
  className?: string
}) {
  const lines = useMemo(() => code.replace(/\n$/, '').split('\n'), [code])

  return (
    <div
      className={cn(
        'relative overflow-auto rounded-md bg-muted/80 p-3',
        compact ? 'max-h-80' : 'max-h-52'
      )}
    >
      <pre className={cn('min-w-0', className)}>
        <code className="font-mono text-xs leading-5">
          {lines.map((line, lineIndex) => (
            <span key={`${line}-${lineIndex}`} className="table-row">
              <span className="table-cell select-none opacity-70 pr-4 text-right">
                {lineIndex + 1}
              </span>
              <span className="table-cell whitespace-pre">
                {tokenizeCodeLine(line).map((token, tokenIndex) => (
                  <span
                    key={`${line}-${lineIndex}-${tokenIndex}`}
                    className={cn(
                      token.className,
                      language ? 'language-' + language : undefined
                    )}
                  >
                    {token.text}
                  </span>
                ))}
              </span>
            </span>
          ))}
        </code>
      </pre>
    </div>
  )
}

function normalizeTableLine(line: string) {
  if (!/[|｜│]/.test(line)) {
    return line
  }

  let normalized = line.replace(/[｜│]/g, '|')
  if (/^\s*\|?[\s|:—–－─-]+\|?\s*$/.test(normalized)) {
    normalized = normalized.replace(/[—–－─]/g, '-')
  }
  return normalized
}

function tableCells(line: string) {
  const normalized = normalizeTableLine(line).trim()
  if (!normalized.includes('|')) {
    return []
  }
  return normalized.replace(/^\|/, '').replace(/\|$/, '').split('|')
}

function isTableCandidateLine(line: string) {
  return tableCells(line).length >= 2
}

function isTableDelimiterLine(line: string) {
  const cells = tableCells(line)
  return cells.length >= 2 && cells.every((cell) => /^:?-{3,}:?$/.test(cell.trim()))
}

function tableDelimiterFor(line: string) {
  return `| ${tableCells(line).map(() => '---').join(' | ')} |`
}

function repairMarkdownTables(content: string) {
  const repaired = content
    .replace(/([*_])\n\1([ \t]*[|｜│])/g, '$1$1$2')

  const lines = repaired.split('\n')
  const output: string[] = []
  let inFence = false
  let inTable = false

  for (let index = 0; index < lines.length; index += 1) {
    const rawLine = lines[index]
    if (/^\s*```/.test(rawLine)) {
      inFence = !inFence
      inTable = false
      output.push(rawLine)
      continue
    }

    if (inFence) {
      output.push(rawLine)
      continue
    }

    if (!rawLine.trim()) {
      const nextLine = lines[index + 1] ? normalizeTableLine(lines[index + 1]) : ''
      if (inTable && isTableCandidateLine(nextLine)) {
        continue
      }
      inTable = false
      output.push(rawLine)
      continue
    }

    const line = normalizeTableLine(rawLine)
    const isTableLine = isTableCandidateLine(line)
    if (!isTableLine) {
      inTable = false
      output.push(line)
      continue
    }

    const nextLine = lines[index + 1] ? normalizeTableLine(lines[index + 1]) : ''
    output.push(line)
    if (
      !inTable &&
      isTableCandidateLine(nextLine) &&
      !isTableDelimiterLine(nextLine)
    ) {
      output.push(tableDelimiterFor(line))
    }
    inTable = true
  }

  return output.join('\n')
}

function splitRunOnMarkdownBlocks(content: string) {
  const lines = content.split('\n')
  let inFence = false

  return lines
    .map((line) => {
      if (/^\s*```/.test(line)) {
        inFence = !inFence
        return line
      }
      if (inFence || isTableCandidateLine(line)) {
        return line
      }
      return line
        .replace(/([^\n])([ \t]+)(#{1,6}\s+)/g, '$1\n\n$3')
        .replace(/([^\n])([ \t]+)([-*+]\s+)/g, '$1\n$3')
        .replace(/([^\n])([ \t]+)(\d+\.\s+)/g, '$1\n$3')
    })
    .join('\n')
}

export function normalizeMarkdownContent(content: string) {
  const unwrapMarkdownFence = (value: string) => {
    const fencedMarkdown = value.match(/^```(?:markdown|md|mdx)?\s*\n([\s\S]*?)\n```$/i)
    return fencedMarkdown?.[1] ? fencedMarkdown[1].trim() : value
  }

  const decodeJsonString = (value: string) => {
    const trimmed = value.trim()
    if (!/^["']/.test(trimmed)) {
      return trimmed
    }
    try {
      const decoded = JSON.parse(trimmed)
      return typeof decoded === 'string' ? decoded.trim() : trimmed
    } catch {
      return trimmed
    }
  }

  let normalized = unwrapMarkdownFence(decodeJsonString(content))
  const escapedNewlineCount = (normalized.match(/\\n/g) || []).length
  if (escapedNewlineCount > 1 || (!normalized.includes('\n') && escapedNewlineCount > 0)) {
    normalized = normalized
      .replace(/\\r\\n/g, '\n')
      .replace(/\\n/g, '\n')
      .replace(/\\t/g, '  ')
  }

  normalized = repairMarkdownTables(unwrapMarkdownFence(normalized).replace(/[ \t]+$/gm, ''))
  normalized = splitRunOnMarkdownBlocks(normalized)

  return repairMarkdownTables(normalized)
    .replace(/(^|\n)[ \t]*#{1,6}[ \t]*(?=\n)/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

export function MarkdownLikeAsset({
  content,
  compact = false,
  compactHeight = 'max-h-[540px]',
}: {
  content: string
  compact?: boolean
  compactHeight?: string
}) {
  const renderedContent = useMemo(() => normalizeMarkdownContent(content), [content])

  return (
    <article
      className={cn(
        'overflow-auto rounded-md border bg-background p-4 text-sm leading-7 text-foreground',
        compact ? 'max-h-80' : compactHeight
      )}
    >
      <ReactMarkdown
        remarkPlugins={[remarkGfm, remarkMath]}
        rehypePlugins={[rehypeKatex]}
        components={{
          h1: ({ children }) => (
            <h1 className="mb-4 mt-1 break-words text-2xl font-semibold leading-8">
              {children}
            </h1>
          ),
          h2: ({ children }) => (
            <h2 className="mb-3 mt-6 break-words border-b pb-2 text-xl font-semibold leading-7">
              {children}
            </h2>
          ),
          h3: ({ children }) => (
            <h3 className="mb-2 mt-5 break-words text-base font-semibold leading-6">
              {children}
            </h3>
          ),
          h4: ({ children }) => (
            <h4 className="mb-2 mt-4 break-words text-sm font-semibold leading-6">
              {children}
            </h4>
          ),
          p: ({ children }) => <p className="my-3 whitespace-pre-wrap break-words leading-7">{children}</p>,
          ul: ({ children }) => (
            <ul className="my-3 list-disc space-y-1 pl-6">{children}</ul>
          ),
          ol: ({ children }) => (
            <ol className="my-3 list-decimal space-y-1 pl-6">{children}</ol>
          ),
          li: ({ children }) => <li className="whitespace-pre-wrap pl-1 leading-7">{children}</li>,
          blockquote: ({ children }) => (
            <blockquote className="my-4 border-l-4 border-primary/40 bg-muted/40 px-4 py-2 text-muted-foreground">
              {children}
            </blockquote>
          ),
          hr: () => <hr className="my-6 border-border" />,
          a: ({ href, children }) => (
            <a
              href={href}
              target="_blank"
              rel="noreferrer"
              className="font-medium text-primary underline-offset-4 hover:underline"
            >
              {children}
            </a>
          ),
          strong: ({ children }) => <strong className="font-semibold">{children}</strong>,
          table: ({ children }) => (
            <div className="my-4 overflow-x-auto">
              <table className="min-w-full border-collapse border border-border">{children}</table>
            </div>
          ),
          thead: ({ children }) => <thead className="bg-muted">{children}</thead>,
          tbody: ({ children }) => <tbody>{children}</tbody>,
          tr: ({ children }) => <tr className="border-b border-border">{children}</tr>,
          th: ({ children }) => (
            <th className="border border-border px-3 py-2 text-left font-semibold">
              {children}
            </th>
          ),
          td: ({ children }) => <td className="border border-border px-3 py-2">{children}</td>,
          pre: ({ children }) => <>{children}</>,
          code: ({ className, children }) => {
            const rawCode = String(children)
            const languageMatch = /language-([\w-]+)/.exec(className || '')
            const isCodeBlock = Boolean(languageMatch) || rawCode.includes('\n')

            if (!isCodeBlock) {
              return (
                <code className="rounded bg-muted px-1 py-0.5 text-sm">{children}</code>
              )
            }
            const language = languageMatch ? languageMatch[1] : undefined
            return (
              <CodeHighlightedBlock
                compact={compact}
                language={language}
                code={rawCode.replace(/\n$/, '')}
                className={className}
              />
            )
          },
        }}
      >
        {renderedContent}
      </ReactMarkdown>
    </article>
  )
}

function QuizAsset({
  resource,
  compact = false,
  onLearningEvent,
}: {
  resource: LearningResource
  compact?: boolean
  onLearningEvent?: (event: LearningAssetInteractionEvent) => void
}) {
  const [answers, setAnswers] = useState<Record<string, number>>({})
  const [currentIndex, setCurrentIndex] = useState(0)
  const questions = getQuizQuestions(resource)
  const currentQuestion = questions[Math.min(currentIndex, questions.length - 1)]
  const answeredCount = Object.keys(answers).length
  const score = questions.reduce((total, question) => {
    return total + (answers[question.id] === question.answer_index ? 1 : 0)
  }, 0)

  if (questions.length === 0 || !currentQuestion) {
    return <MarkdownLikeAsset content={resource.content} compact={compact} compactHeight="max-h-80" />
  }

  const handleAnswer = (
    question: QuizQuestion,
    questionIndex: number,
    optionIndex: number
  ) => {
    const nextAnswers = {
      ...answers,
      [question.id]: optionIndex,
    }
    setAnswers(nextAnswers)

    const nextScore = questions.reduce((total, item) => {
      return total + (nextAnswers[item.id] === item.answer_index ? 1 : 0)
    }, 0)
    const correct = optionIndex === question.answer_index
    onLearningEvent?.({
      eventType: 'quiz_answer',
      summary: `Quiz "${resource.title}" question ${questionIndex + 1}/${questions.length} ${
        correct ? 'correct' : 'incorrect'
      } score ${nextScore}/${questions.length}. Prompt: ${question.prompt}`,
    })
  }

  const selected = answers[currentQuestion.id]
  const answered = selected !== undefined

  return (
    <div
      className={cn(
        'space-y-3',
        compact ? 'max-h-80 overflow-y-auto pr-1' : 'max-h-[calc(90vh-220px)] overflow-y-auto pr-1'
      )}
    >
      <div className="flex items-center justify-between rounded-md border bg-muted/40 px-3 py-2 text-sm">
        <span>{currentIndex + 1}/{questions.length}</span>
        <span className="font-medium">Score {score}/{questions.length}</span>
      </div>
      <div className="rounded-lg border p-3">
        <p className="text-sm font-medium">
          {currentIndex + 1}. {currentQuestion.prompt}
        </p>
        <div className="mt-3 grid gap-2">
          {currentQuestion.options.map((option, optionIndex) => {
            const isSelected = selected === optionIndex
            const isCorrect = currentQuestion.answer_index === optionIndex
            return (
              <button
                key={`${currentQuestion.id}-${optionIndex}`}
                type="button"
                onClick={() => handleAnswer(currentQuestion, currentIndex, optionIndex)}
                className={cn(
                  'rounded-md border px-3 py-2 text-left text-sm transition-colors',
                  answered &&
                    isCorrect &&
                    'border-emerald-500 bg-emerald-50 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200',
                  answered &&
                    isSelected &&
                    !isCorrect &&
                    'border-destructive bg-destructive/10 text-destructive',
                  !answered && 'hover:bg-muted'
                )}
              >
                {option}
              </button>
            )
          })}
        </div>
        {answered && (
          <p className="mt-3 rounded-md bg-muted px-3 py-2 text-sm">
            {currentQuestion.explanation}
          </p>
        )}
      </div>
      <div className="flex items-center justify-between gap-2">
        <span className="text-xs text-muted-foreground">
          Answered {answeredCount}/{questions.length}
        </span>
        <div className="flex gap-2">
          <Button
            type="button"
            variant="outline"
            size="sm"
            disabled={currentIndex === 0}
            onClick={() => setCurrentIndex((index) => Math.max(0, index - 1))}
          >
            Prev
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            disabled={currentIndex === questions.length - 1}
            onClick={() => setCurrentIndex((index) => Math.min(questions.length - 1, index + 1))}
          >
            Next
          </Button>
        </div>
      </div>
    </div>
  )
}

function FlashcardAsset({ resource, compact = false }: { resource: LearningResource; compact?: boolean }) {
  const [flipped, setFlipped] = useState<Record<number, boolean>>({})
  const [currentIndex, setCurrentIndex] = useState(0)
  const cards = getFlashcards(resource)
  const currentCard = cards[Math.min(currentIndex, cards.length - 1)]

  if (cards.length === 0 || !currentCard) {
    return <MarkdownLikeAsset content={resource.content} compact={compact} compactHeight="max-h-80" />
  }

  const isFlipped = flipped[currentIndex]

  return (
    <div
      className={cn(
        'space-y-3',
        compact ? 'max-h-80 overflow-y-auto pr-1' : 'max-h-[calc(90vh-220px)] overflow-y-auto pr-1'
      )}
    >
      <div className="rounded-lg border p-4">
        <p className="text-xs font-medium text-muted-foreground">
          Card {currentIndex + 1}/{cards.length}
        </p>
        <p className="mt-3 min-h-24 text-sm leading-6">
          {isFlipped ? currentCard.back : currentCard.front}
        </p>
        {!isFlipped && currentCard.hint && (
          <p className="mt-2 rounded-md bg-muted px-3 py-2 text-xs text-muted-foreground">
            Hint: {currentCard.hint}
          </p>
        )}
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="mt-3"
          onClick={() =>
            setFlipped((previous) => ({
              ...previous,
              [currentIndex]: !previous[currentIndex],
            }))
          }
        >
          {isFlipped ? 'Back' : 'Answer'}
        </Button>
      </div>
      <div className="flex justify-end gap-2">
        <Button
          type="button"
          variant="outline"
          size="sm"
          disabled={currentIndex === 0}
          onClick={() => setCurrentIndex((index) => Math.max(0, index - 1))}
        >
          Prev
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          disabled={currentIndex === cards.length - 1}
          onClick={() => setCurrentIndex((index) => Math.min(cards.length - 1, index + 1))}
        >
          Next
        </Button>
      </div>
    </div>
  )
}

function normalizeMindMapText(rawText: string) {
  const withoutClass = rawText.replace(/:::[A-Za-z0-9_-]+/g, '').trim()
  const withoutIcon = withoutClass.replace(/::icon\([^)]+\)/g, '').trim()
  const wrapped = [
    withoutIcon.match(/^[A-Za-z0-9_-]+\(\((.*)\)\)$/),
    withoutIcon.match(/^[A-Za-z0-9_-]+\((.*)\)$/),
    withoutIcon.match(/^[A-Za-z0-9_-]+\[(.*)\]$/),
    withoutIcon.match(/^[A-Za-z0-9_-]+\{\{(.*)\}\}$/),
  ].find(Boolean)

  return (wrapped?.[1] ?? withoutIcon).trim()
}

function parseMindMapNodes(content: string) {
  const normalizedContent = content
    .trim()
    .replace(/^```(?:mermaid|mindmap)?\s*\n([\s\S]*?)\n```$/i, '$1')
    .trim()
  const lines = normalizedContent.split('\n')
  const roots: MindMapNode[] = []
  const stack: Array<{ level: number; node: MindMapNode }> = []
  let inCodeFence = false
  let inMermaidMindMap = false
  let cursor = 0

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) {
      continue
    }

    if (trimmed.startsWith('```')) {
      inCodeFence = !inCodeFence
      continue
    }
    if (inCodeFence) {
      continue
    }

    if (/^mindmap(?:\s|$)/i.test(trimmed)) {
      inMermaidMindMap = true
      continue
    }

    const headingMatch = line.match(/^(\s*)(#{1,6})\s+(.*)$/)
    const listMatch = line.match(/^([ \t]*)(?:[-*+]|\d+\.)\s+(.*)$/)
    const mermaidMatch = inMermaidMindMap
      ? line.match(/^([ \t]*)(?!%%)(?!classDef\b)(?!class\b)(?!style\b)(.+)$/)
      : null

    if (!headingMatch && !listMatch && !mermaidMatch) {
      continue
    }

    const rawText =
      headingMatch?.[3]?.trim() ??
      listMatch?.[2]?.trim() ??
      mermaidMatch?.[2]?.trim() ??
      ''
    const text = normalizeMindMapText(rawText)
    if (!text) {
      continue
    }

    const indentLevel = headingMatch
      ? Math.max(0, headingMatch[2].length - 1)
      : Math.max(
          0,
          Math.floor(
            (listMatch?.[1] ?? mermaidMatch?.[1] ?? '').replace(/\t/g, '    ').length / 2
          ) + (mermaidMatch ? 0 : 1)
        )
    const level = indentLevel

    const node: MindMapNode = {
      id: `${text}-${cursor}-${level}-${roots.length}`,
      text,
      level,
      children: [],
    }
    cursor += 1

    while (stack.length > 0 && stack[stack.length - 1].level >= level) {
      stack.pop()
    }

    if (stack.length > 0) {
      stack[stack.length - 1].node.children.push(node)
    } else {
      roots.push(node)
    }

    stack.push({ level, node })
  }

  return roots
}

function isProfileArtifactMindMapContent(content: string) {
  const compact = content.toLowerCase()
  return (
    compact.includes('learning_profile') ||
    /(^|\n)\s*-\s*id:\s*source:/i.test(content) ||
    content.includes('学习画像')
  )
}

function MindMapNodeView({ node, depth = 0 }: { node: MindMapNode; depth?: number }) {
  return (
    <div className="flex min-w-0 flex-col items-center">
      <div
        className={cn(
          'min-w-32 max-w-56 rounded-md border px-3 py-2 text-center shadow-sm',
          depth === 0
            ? 'border-primary/40 bg-primary text-primary-foreground'
            : depth === 1
              ? 'bg-muted'
              : 'bg-background'
        )}
      >
        <p className={cn('break-words text-sm leading-5', depth === 0 && 'font-semibold')}>
          {node.text}
        </p>
      </div>
      {node.children.length > 0 && (
        <>
          <div className="h-5 w-px bg-border" />
          <div
            className={cn(
              'grid w-full gap-3',
              node.children.length === 1
                ? 'grid-cols-1 justify-items-center'
                : 'grid-cols-[repeat(auto-fit,minmax(8.5rem,1fr))]'
            )}
          >
          {node.children.map((child) => (
            <div key={child.id} className="relative flex justify-center">
              <span className="absolute -top-3 left-1/2 h-3 w-px -translate-x-1/2 bg-border" />
              <MindMapNodeView node={child} depth={depth + 1} />
            </div>
          ))}
          </div>
        </>
      )}
    </div>
  )
}

function MindMapAsset({ content, compact = false }: { content: string; compact?: boolean }) {
  const nodes = useMemo(() => parseMindMapNodes(content), [content])

  if (nodes.length === 0 || isProfileArtifactMindMapContent(content)) {
    return (
      <MarkdownLikeAsset
        content={
          isProfileArtifactMindMapContent(content)
            ? '这条思维导图内容来自学习画像元数据，不适合作为知识导图渲染。请重新生成该资产。'
            : content
        }
        compact={compact}
        compactHeight="max-h-80"
      />
    )
  }

  return (
    <article
      className={cn(
        'overflow-auto rounded-md border bg-background p-4',
        compact ? 'max-h-80' : 'max-h-[540px]'
      )}
    >
      <div className={cn('min-w-[560px] space-y-6', compact && 'min-w-[460px]')}>
        {nodes.map((node) => (
          <MindMapNodeView key={node.id} node={node} />
        ))}
      </div>
    </article>
  )
}

export function LearningAssetPreview({
  resource,
  compact = false,
  onLearningEvent,
}: {
  resource: LearningResource
  compact?: boolean
  onLearningEvent?: (event: LearningAssetInteractionEvent) => void
}) {
  if (resource.kind === 'quiz') {
    return <QuizAsset resource={resource} compact={compact} onLearningEvent={onLearningEvent} />
  }
  if (resource.kind === 'flashcards') {
    return <FlashcardAsset resource={resource} compact={compact} />
  }
  if (resource.kind === 'mind_map') {
    return <MindMapAsset content={resource.content} compact={compact} />
  }
  return (
    <MarkdownLikeAsset
      content={resource.content}
      compact={compact}
      compactHeight={resource.kind === 'code_lab' ? 'max-h-52' : 'max-h-[540px]'}
    />
  )
}
