import type {
  LearningCollectedResource,
  LearningResource,
} from '@/lib/types/learning'

export const AI_LEARNING_DEMO_TOTAL_STEPS = 15

export type AiLearningDemoScene = 'notebook' | 'search' | 'workflow' | 'studio'
export type AiLearningDemoAssetId =
  | 'blog'
  | 'mind-map'
  | 'podcast'
  | 'quiz'
  | 'visual-aid'
  | 'video'

export const AI_LEARNING_DEMO_STEPS = [
  { step: 0, scene: 'notebook', label: '创建学习记录', href: '/notebooks/ai-learning-demo' },
  { step: 1, scene: 'notebook', label: '画像访谈', href: '/notebooks/ai-learning-demo?step=1' },
  { step: 2, scene: 'notebook', label: '建立画像', href: '/notebooks/ai-learning-demo?step=2' },
  { step: 3, scene: 'notebook', label: '空学习空间', href: '/notebooks/ai-learning-demo?step=3' },
  { step: 4, scene: 'notebook', label: '提出问题', href: '/notebooks/ai-learning-demo?step=4' },
  { step: 5, scene: 'notebook', label: '个性化回答', href: '/notebooks/ai-learning-demo?step=5' },
  { step: 6, scene: 'search', label: '准备搜集资料', href: '/notebooks/ai-learning-demo?step=6' },
  { step: 7, scene: 'search', label: '搜集外部资料', href: '/notebooks/ai-learning-demo?step=7' },
  { step: 8, scene: 'search', label: '采纳资料', href: '/notebooks/ai-learning-demo?step=8' },
  { step: 9, scene: 'workflow', label: 'Agent 调度', href: '/workflow/ai-learning-demo?step=9' },
  { step: 10, scene: 'workflow', label: '多智能体协作', href: '/workflow/ai-learning-demo?step=10' },
  { step: 11, scene: 'workflow', label: '工作流完成', href: '/workflow/ai-learning-demo?step=11' },
  { step: 12, scene: 'studio', label: '生成多模态资产', href: '/notebooks/ai-learning-demo?step=12' },
  { step: 13, scene: 'studio', label: '多模态资产就绪', href: '/notebooks/ai-learning-demo?step=13' },
  { step: 14, scene: 'studio', label: 'Quiz 评估', href: '/notebooks/ai-learning-demo?step=14' },
  { step: 15, scene: 'studio', label: '画像回写', href: '/notebooks/ai-learning-demo?step=15' },
] as const satisfies ReadonlyArray<{
  step: number
  scene: AiLearningDemoScene
  label: string
  href: string
}>

export function demoStepHref(step: number) {
  const safeStep = Math.max(0, Math.min(AI_LEARNING_DEMO_TOTAL_STEPS, step))
  return AI_LEARNING_DEMO_STEPS[safeStep].href
}

export function defaultDemoStepForPath(pathname: string | null) {
  if (pathname?.startsWith('/workflow/')) return 9
  return 0
}

export const AI_LEARNING_DEMO = {
  notebookName: 'ai学习',
  topic: '理解 Transformer 的 Q、K、V 与注意力机制',
  profileQuestion:
    '开始前想先了解一下：你目前对注意力机制掌握到什么程度，更喜欢怎样的讲解方式？',
  profileAnswer:
    '我会 Python，也学过基础神经网络。知道注意力会给信息分配权重，但还不清楚 Q、K、V 为什么这样设计。我更喜欢图解、类比和能运行的代码。',
  profileDimensions: [
    { label: '知识基础', value: '机器学习入门', score: 72 },
    { label: '认知偏好', value: '图解与类比', score: 88 },
    { label: '学习目标', value: '理解并实现', score: 81 },
    { label: '学习节奏', value: '短路径实践', score: 84 },
    { label: '动机水平', value: '项目驱动', score: 79 },
    { label: '反馈偏好', value: '即时纠错', score: 86 },
    { label: '当前瓶颈', value: '张量关系', score: 64 },
    { label: '迁移能力', value: '需要示例', score: 68 },
  ],
  userQuestion:
    '能不能用一个直观例子解释 Q、K、V，再告诉我它们如何一起算出注意力？',
  assistantAnswer:
    '可以把它想成一次“带着问题查索引”：Q 是你此刻想找什么，K 是每条信息的索引标签，V 是信息本身。Q 与所有 K 比较得到相关度，再用这些权重混合 V。接下来我会用权威资料、动态图解和一段 PyTorch 代码把这条链路验证完整。',
  searchQuery: 'Transformer Q K V 注意力机制 图解 PyTorch 实现',
  searchIntents: [
    {
      agent: 'Scholar Agent',
      intent: '追溯原始公式与设计依据',
      scope: '论文 / 引用网络',
      result: '定位缩放点积注意力原始定义',
    },
    {
      agent: 'Web Agent',
      intent: '寻找适合图解型学习者的解释',
      scope: '教程 / 课程 / 动画',
      result: '筛选出 2 个高质量可视化教程',
    },
    {
      agent: 'Code Agent',
      intent: '验证张量形状与可运行实现',
      scope: '官方文档 / 代码仓库',
      result: '确认 PyTorch MultiheadAttention 接口',
    },
  ],
  sources: [
    {
      title: 'Attention Is All You Need',
      kind: '论文',
      meta: '论文 · Vaswani et al. · 2017',
      domain: 'arXiv',
      score: 98,
      insight: '给出 scaled dot-product attention 与 multi-head attention 的原始定义。',
      recommendation: '原始定义，作为公式与事实基线',
    },
    {
      title: 'The Illustrated Transformer',
      kind: '图解',
      meta: '图解教程 · Jay Alammar',
      domain: 'jalammar.github.io',
      score: 96,
      insight: '用逐帧可视化串起 Q、K、V、softmax 与信息聚合。',
      recommendation: '高度匹配“图解 + 类比”的认知偏好',
    },
    {
      title: 'MultiheadAttention — PyTorch',
      kind: '代码',
      meta: '官方文档 · PyTorch 2.x',
      domain: 'pytorch.org',
      score: 94,
      insight: '提供张量形状、参数说明和可运行实现接口。',
      recommendation: '对应“理解并实现”的学习目标',
    },
    {
      title: 'Attention for Neural Networks, Clearly Explained!!!',
      kind: '视频',
      meta: '讲解视频 · StatQuest · 15:50',
      domain: 'youtube.com',
      score: 92,
      insight: '用动画和逐步推导解释 Query、Key、Value 的信息流。',
      recommendation: '适合在播客前进行一次视听预习',
    },
  ],
  evidenceSummary:
    '4 个独立来源在“Q 与 K 计算相关性、softmax 归一化、再对 V 加权求和”这一核心链路上相互印证；原论文负责定义，官方文档验证实现，图解教程匹配当前画像。',
  workflowAgents: [
    {
      id: 'profile-agent',
      name: '学习画像智能体',
      role: '读取 8 维画像与当前知识缺口',
      duration: '0.8 秒',
    },
    {
      id: 'resource-agent',
      name: '资源生成智能体',
      role: '基于已采纳来源生成讲解、导图、Quiz 与视觉辅助',
      duration: '10.2 秒',
    },
    {
      id: 'safety-agent',
      name: '安全校验智能体',
      role: '执行来源追溯、防幻觉与内容安全校验',
      duration: '1.6 秒',
    },
  ],
  assets: [
    {
      id: 'blog',
      type: '学习博客',
      title: '为什么注意力不是“查字典”？用一组数字真正算懂 Q、K、V',
      meta: '8 分钟阅读 · 4 个可追溯引用',
      description: '类比 → 公式 → 张量形状 → PyTorch 实现',
    },
    {
      id: 'mind-map',
      type: '思维导图',
      title: '注意力机制知识地图',
      meta: '12 个节点 · 3 层关系',
      description: '把 Q、K、V、相似度、softmax 与输出串成一张图',
    },
    {
      id: 'podcast',
      type: '学习播客',
      title: '为什么注意力需要 Q、K、V？',
      meta: '约 1 分钟 · 自然中文讲解',
      description: '用图书馆检索类比串讲注意力计算流程',
    },
    {
      id: 'quiz',
      type: 'Quiz',
      title: 'QKV 概念诊断',
      meta: '即时作答 · 错题本与证据定位',
      description: '检验相关性计算、权重归一化与 Value 聚合',
    },
    {
      id: 'visual-aid',
      type: '辅助图片',
      title: 'QKV 信息流一图读懂',
      meta: '1600 × 900 · 可放大与导出',
      description: '用颜色区分查询、匹配、归一化与信息聚合',
    },
    {
      id: 'video',
      type: '讲解视频',
      title: '1 分钟看懂一次注意力计算',
      meta: '可播放 MP4 · 720p · 内嵌与可选字幕',
      description: '动态图解 QKᵀ、softmax 与 Value 加权',
    },
  ] satisfies ReadonlyArray<{
    id: AiLearningDemoAssetId
    type: string
    title: string
    meta: string
    description: string
  }>,
  guideSections: [
    'Q 是当前 token 发出的检索请求',
    'K 描述每个 token 能被怎样匹配',
    'softmax 将 QKᵀ 转成注意力权重',
    '权重与 V 相乘，得到按需聚合的上下文',
  ],
  mindMapBranches: [
    { label: 'Query', detail: '我想找什么' },
    { label: 'Key', detail: '我能匹配什么' },
    { label: 'Value', detail: '我携带的信息' },
    { label: 'Attention', detail: '相关性 → 权重 → 聚合' },
  ],
  podcast: {
    title: '为什么注意力需要 Q、K、V？',
    duration: '00:51',
    currentTime: '00:00',
    transcript:
      '把 Query 想成读者手里的问题，Key 是书架索引，而 Value 才是书中真正要取出的内容。',
  },
  quiz: {
    question: '当某个 Query 与一个 Key 的相似度更高时，后续最可能发生什么？',
    options: [
      '对应 Value 在输出中的占比提高',
      '对应 Value 会被直接删除',
      'Query 的维度会自动增加',
      '所有 Key 的权重都会变成零',
    ],
    answer: '对应 Value 在输出中的占比提高',
    explanation:
      'QKᵀ 的相似度经过 softmax 后成为权重；相似度越高，对应 Value 在加权和中的贡献通常越大。',
  },
  profileUpdate: {
    dimension: '概念理解',
    before: 72,
    after: 80,
    evidence: '完成 QKV Quiz，正确解释注意力权重如何影响 Value 聚合。',
    next: '进入 Multi-Head Attention：理解不同注意力头如何学习互补关系。',
  },
} as const

export const AI_LEARNING_DEMO_COLLECTED_RESOURCES = [
  {
    id: 'demo-source-attention-paper',
    title: 'Attention Is All You Need',
    source_type: 'web',
    query: AI_LEARNING_DEMO.searchQuery,
    reason: '原始定义，作为公式与事实基线',
    url: 'https://arxiv.org/abs/1706.03762',
    snippet: '给出 scaled dot-product attention 与 multi-head attention 的原始定义。',
    provider: 'arXiv',
    quality_score: 0.98,
    resource_kind: 'research_paper',
    learning_value: '用于核验 Q、K、V 与缩放点积注意力的定义和公式。',
    search_intent: '追溯原始公式',
    content_type: 'paper',
    tags: ['原论文', '公式基线'],
    adoption_status: 'recommended',
  },
  {
    id: 'demo-source-illustrated-transformer',
    title: 'The Illustrated Transformer',
    source_type: 'web',
    query: AI_LEARNING_DEMO.searchQuery,
    reason: '高度匹配“图解 + 类比”的认知偏好',
    url: 'https://jalammar.github.io/illustrated-transformer/',
    snippet: '用逐帧可视化串起 Q、K、V、softmax 与信息聚合。',
    provider: 'Jay Alammar',
    quality_score: 0.96,
    resource_kind: 'visual_tutorial',
    learning_value: '适合先建立图形直觉，再回到矩阵计算。',
    search_intent: '寻找图解教程',
    content_type: 'article',
    tags: ['图解', '认知适配'],
    adoption_status: 'recommended',
  },
  {
    id: 'demo-source-pytorch-mha',
    title: 'MultiheadAttention — PyTorch',
    source_type: 'web',
    query: AI_LEARNING_DEMO.searchQuery,
    reason: '对应“理解并实现”的学习目标',
    url: 'https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html',
    snippet: '提供张量形状、参数说明和可运行实现接口。',
    provider: 'PyTorch',
    quality_score: 0.94,
    resource_kind: 'official_documentation',
    learning_value: '用于把公式映射到可运行的 PyTorch 接口和张量形状。',
    search_intent: '验证代码实现',
    content_type: 'code',
    tags: ['官方文档', '代码'],
    adoption_status: 'recommended',
  },
  {
    id: 'demo-source-statquest-video',
    title: 'Attention for Neural Networks, Clearly Explained!!!',
    source_type: 'web',
    query: AI_LEARNING_DEMO.searchQuery,
    reason: '适合在播客前进行一次视听预习',
    url: 'https://www.youtube.com/watch?v=PSs6nxngL6k',
    snippet: '用动画和逐步推导解释 Query、Key、Value 的信息流。',
    provider: 'YouTube · StatQuest',
    quality_score: 0.92,
    resource_kind: 'video_lecture',
    learning_value: '通过口语讲解和动画强化 QKV 的信息流直觉。',
    search_intent: '寻找视频讲解',
    content_type: 'video',
    tags: ['视频', '动画'],
    adoption_status: 'recommended',
  },
] satisfies LearningCollectedResource[]

export const AI_LEARNING_DEMO_RESOURCES = {
  blog: {
    kind: 'blog',
    type: '学习博客',
    title: '为什么注意力不是“查字典”？用一组数字真正算懂 Q、K、V',
    agent: '资源生成智能体',
    format: 'Markdown + 引用',
    summary:
      '从检索类比切入，再用一个二维数值例子完整走过缩放、softmax 与 Value 加权。公式、张量形状和 PyTorch 代码均锚定原论文与官方文档，最后用三步自检确认是否真正理解。',
    content: [
      '# 为什么注意力不是“查字典”？用一组数字真正算懂 Q、K、V',
      '',
      '> 你可能已经记住了“Q 是查询、K 是键、V 是值”，却仍然回答不了：**为什么相似度最后要乘 V？为什么还要除以 $\\sqrt{d_k}$？** 这篇文章不再背名词，而是把一次注意力计算真正算到底。',
      '',
      '![注意力从检索候选到聚合信息的视觉类比](/demo/ai-learning/attention-searchlight.png)',
      '',
      '*Query 像一束检索光：它先与候选 Key 建立相关性，再让对应的 Value 按权重汇入输出。下文会说明这个类比的边界。*',
      '',
      '读完后，你应该能做到：',
      '',
      '- 不靠口诀解释 Q、K、V 各自承担的计算角色；',
      '- 根据张量形状写出 $QK^T$ 和加权求和；',
      '- 手算一个两候选注意力例子，并判断输出为什么偏向某个 Value；',
      '- 识别“最高分就是硬选择”等常见误区。',
      '',
      '## 1. 先建立直觉：检索的是“相关程度”，取回的是“内容”',
      '',
      '把当前 token 想成一位带着问题走进图书馆的读者：',
      '',
      '- **Query（Q）**描述“我现在需要什么”；',
      '- **Key（K）**描述“每条候选信息适合被什么问题匹配”；',
      '- **Value（V）**才是匹配后真正被带回去、参与下一层表示的内容。',
      '',
      '这个类比最重要的边界是：注意力并不是从数据库中硬取回一条记录。它会对所有候选的 Value 做**连续的加权求和**，而且 Q、K、V 都是从输入表示经可学习线性变换得到的向量。原论文把这一步定义为 Scaled Dot-Product Attention（来源：[Attention Is All You Need，3.2.1](https://arxiv.org/abs/1706.03762)）。',
      '',
      '## 2. 公式不是终点：每个维度到底在做什么',
      '',
      '$$\\operatorname{Attention}(Q,K,V)=\\operatorname{softmax}\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V$$',
      '',
      '用多头注意力中常见的批量形状表示：',
      '',
      '- $Q:[B,H,L_q,d_k]$，其中 $L_q$ 是发起查询的 token 数；',
      '- $K:[B,H,L_k,d_k]$，转置最后两维后与 Q 相乘；',
      '- $QK^T:[B,H,L_q,L_k]$，每个 Query 都得到一行“对所有 Key 的匹配分数”；',
      '- softmax 沿 $L_k$ 维归一化，得到同形状的权重；',
      '- 若 $V:[B,H,L_k,d_v]$，最终输出为 $[B,H,L_q,d_v]$。',
      '',
      '为什么除以 $\\sqrt{d_k}$？原论文指出，当 $d_k$ 较大时，点积的量级容易增大，把 softmax 推入梯度很小的区域；缩放让分数保持在更合适的范围（来源：[原论文 3.2.1](https://arxiv.org/abs/1706.03762)）。',
      '',
      '## 3. 手算一次：两个候选如何共同决定输出',
      '',
      '下面是依照原论文公式构造的二维算例。设一个 Query 面对两个候选：',
      '',
      '$$Q=[1,0],\\quad K_1=[1,0],\\quad K_2=[0,1]$$',
      '$$V_1=[2,0],\\quad V_2=[0,4],\\quad d_k=2$$',
      '',
      '第一步，点积并缩放：',
      '',
      '$$s=\\frac{QK^T}{\\sqrt{2}}=\\left[\\frac{1}{\\sqrt{2}},0\\right]\\approx[0.707,0]$$',
      '',
      '第二步，softmax 把分数变成权重：',
      '',
      '$$\\alpha=\\operatorname{softmax}(s)\\approx[0.67,0.33]$$',
      '',
      '第三步，用权重混合 Value：',
      '',
      '$$o=0.67V_1+0.33V_2\\approx[1.34,1.32]$$',
      '',
      '关键观察：$K_1$ 更匹配，所以 $V_1$ 的贡献更大；但 $V_2$ 没有消失。注意力输出是“按相关程度混合内容”，不是 winner-takes-all 的硬检索。',
      '',
      '## 4. 把手算翻译成可运行的 PyTorch',
      '',
      '```python',
      'import math',
      'import torch',
      '',
      'q = torch.tensor([[1.0, 0.0]])       # [Lq=1, dk=2]',
      'k = torch.tensor([[1.0, 0.0],',
      '                  [0.0, 1.0]])       # [Lk=2, dk=2]',
      'v = torch.tensor([[2.0, 0.0],',
      '                  [0.0, 4.0]])       # [Lk=2, dv=2]',
      '',
      'scores = q @ k.transpose(-2, -1) / math.sqrt(k.size(-1))',
      'weights = scores.softmax(dim=-1)',
      'context = weights @ v',
      '',
      'print(weights)  # tensor([[0.6698, 0.3302]])',
      'print(context)  # tensor([[1.3395, 1.3209]])',
      '```',
      '',
      '正式工程中还要处理批次、多头、mask 和 dropout。PyTorch 的 `scaled_dot_product_attention` 与 `MultiheadAttention` 提供了这些标准接口（来源：[PyTorch MultiheadAttention](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html)）。',
      '',
      '## 5. 一张表分清角色，也分清误区',
      '',
      '| 对象 | 它参与什么计算 | 它不是什么 |',
      '| --- | --- | --- |',
      '| Query | 与所有 Key 计算匹配分数 | 最终被取回的内容 |',
      '| Key | 提供可匹配的特征坐标 | 数据库里固定不变的字符串键 |',
      '| Value | 按 softmax 权重参与加权和 | 用来直接计算匹配分数的向量 |',
      '| softmax 权重 | 表示当前 Query 下各 Value 的相对贡献 | 永远只保留最大项的 one-hot 选择 |',
      '',
      '## 6. 三个常见误区',
      '',
      '### 误区一：Q、K、V 是三份不同的原始数据',
      '',
      '在自注意力中，它们通常来自同一组输入表示，但经过不同的可学习投影；在交叉注意力中，Q 与 K/V 才可能来自不同序列。不要把“角色不同”误解成“数据源一定不同”。',
      '',
      '### 误区二：注意力权重越大，就等于模型给出了因果解释',
      '',
      '权重直接描述这次前向计算中的加权比例，但不能仅凭它推出完整的因果解释。本文只把它解释为 Value 对当前输出的计算贡献。',
      '',
      '### 误区三：mask 可以在 softmax 之后把权重乘零',
      '',
      '标准做法是在 softmax 前把被屏蔽位置的分数设为极小值，使归一化后的概率接近零；若在 softmax 后直接清零而不重新归一化，剩余权重之和将不再是 1。',
      '',
      '## 7. 三步自检',
      '',
      '1. **形状检查：** 若 $Q:[2,8,16,64]$、$K:[2,8,32,64]$，$QK^T$ 的形状是什么？',
      '   - 参考答案：$[2,8,16,32]$；每个 Query 位置都要与 32 个 Key 位置比较。',
      '2. **机制检查：** 某个 Key 的相似度提高后，哪个量会直接改变？',
      '   - 参考答案：softmax 后对应的注意力权重通常提高，从而改变对应 Value 在加权和中的贡献。',
      '3. **边界检查：** 为什么“查字典”只是类比？',
      '   - 参考答案：注意力通常不会硬选一条记录，而是对多个 Value 连续加权；Q、K、V 还是学习得到的向量投影。',
      '',
      '> **一句话记忆：** Q 决定要找什么，K 决定如何被匹配，V 决定匹配之后真正带走什么。',
      '',
      '## 来源与继续阅读',
      '',
      '- Vaswani et al., [Attention Is All You Need](https://arxiv.org/abs/1706.03762)，重点阅读 3.2.1 与 3.2.2。',
      '- PyTorch, [MultiheadAttention 官方文档](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html)，用于核对工程接口与张量约定。',
    ].join('\n'),
    tags: ['Transformer', 'QKV', '逐步算例', 'PyTorch', '可追溯'],
    payload: {
      source_count: 2,
      audience: '已经听过 QKV 名词，但仍无法独立推导注意力计算的学习者',
      learning_objectives: ['解释 Q/K/V 角色', '手算缩放点积注意力', '核对张量形状', '排查常见误区'],
      provenance: [
        {
          title: 'Attention Is All You Need',
          url: 'https://arxiv.org/abs/1706.03762',
          location: 'Sections 3.2.1–3.2.2',
        },
        {
          title: 'PyTorch MultiheadAttention',
          url: 'https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html',
        },
      ],
    },
  },
  'mind-map': {
    kind: 'mind_map',
    type: '思维导图',
    title: '注意力机制知识地图',
    agent: '资源生成智能体',
    format: 'Mermaid mindmap',
    summary: '从 Q、K、V 到加权输出的可交互知识地图。',
    content: [
      'mindmap',
      '  root((注意力机制))',
      '    Query',
      '      当前 token 的检索请求',
      '      与所有 Key 计算相似度',
      '    Key',
      '      信息的匹配索引',
      '      决定哪些内容相关',
      '    Value',
      '      被聚合的真实信息',
      '      按注意力权重加权',
      '    计算链路',
      '      QKᵀ',
      '      缩放',
      '      softmax',
      '      乘以 Value',
    ].join('\n'),
    tags: ['Transformer', '思维导图', 'QKV'],
    payload: {},
  },
  quiz: {
    kind: 'quiz',
    type: 'Quiz',
    title: 'QKV 概念诊断',
    agent: '练习实训智能体',
    format: '交互式测验',
    summary: '根据当前画像动态生成的一题快速诊断。',
    content: '',
    tags: ['Quiz', '自适应评估', '画像回写'],
    payload: {
      questions: [
        {
          id: 'qkv-weight',
          prompt: '当某个 Query 与一个 Key 的相似度更高时，后续最可能发生什么？',
          options: [
            '对应 Value 在输出中的占比提高',
            '对应 Value 会被直接删除',
            'Query 的维度会自动增加',
            '所有 Key 的权重都会变成零',
          ],
          answer_index: 0,
          explanation:
            'QKᵀ 的相似度经过 softmax 后成为权重；相似度越高，对应 Value 在加权和中的贡献通常越大。',
          source_title: 'Attention Is All You Need',
          source_ref: 'Section 3.2.1',
          evidence: 'Scaled Dot-Product Attention 对 Value 按 softmax 权重执行加权求和。',
          location: 'Section 3.2.1',
        },
        {
          id: 'qkv-scale',
          prompt: '缩放点积注意力为什么要除以 √dₖ？',
          options: [
            '避免维度较大时点积过大，让 softmax 保持有效梯度',
            '把 Query 的长度固定为一个 token',
            '删除所有负数注意力分数',
            '让 Value 自动变成概率分布',
          ],
          answer_index: 0,
          explanation:
            '当 dₖ 较大时，点积的量级会增大，使 softmax 进入梯度很小的区域；缩放可以改善数值与训练稳定性。',
          source_title: 'Attention Is All You Need',
          source_ref: 'Section 3.2.1',
          evidence: '原论文在 Scaled Dot-Product Attention 中说明了缩放项的动机。',
          location: 'Section 3.2.1',
        },
      ],
    },
  },
  'visual-aid': {
    kind: 'visual_aid',
    type: '辅助图片',
    title: 'QKV 信息流一图读懂',
    agent: '资源生成智能体',
    format: 'SVG · 1600 × 900',
    summary: '用颜色区分查询、匹配、归一化与信息聚合。',
    content: 'QKV 信息流教学图：QKᵀ → 缩放 → softmax → 与 V 相乘。',
    tags: ['QKV', '辅助图片', '可导出'],
    payload: {
      image_src: '/demo/ai-learning/qkv-flow.svg',
      prompt: '深色教学信息图，清晰呈现 Q、K、V 和注意力权重的计算流向。',
    },
  },
} satisfies Record<'blog' | 'mind-map' | 'quiz' | 'visual-aid', LearningResource>

export const AI_LEARNING_DEMO_MEDIA = {
  podcast: '/demo/ai-learning/qkv-podcast.mp3',
  video: '/demo/ai-learning/qkv-explainer.mp4',
  videoCaptions: '/demo/ai-learning/qkv-explainer.vtt',
  poster: '/demo/ai-learning/qkv-flow.svg',
} as const
